### ISSUE TITLE
Doesn't return original Promise like bluebird

### ISSUE THREAD

**Issue by kevinoid** [CrabDude/bluebird-nodeify#1]
It would be worth noting in the documentation, or fixing, the difference in return value between this module and `bluebird.Promise.prototype.nodeify` as demonstrated below:

``` js
var bluebird = require('bluebird');
var nodeify = require('bluebird-nodeify');

bluebird.resolve('Value').nodeify(function() {}).then(console.log);   // Value
nodeify(bluebird.resolve('Value'), function() {}).then(console.log);  // undefined
```

Thanks,
Kevin

**Comment by CrabDude** [comment]
Thanks for pointing that out. I'll have `nodeify` return a promise.

**Comment by kevinoid** [comment]
Great, thanks!

**Comment by kevinoid** [comment]
If you are interested in bluebird compatibility, I also found a difference in the handling of exceptions thrown by the callback (bluebird will preserve `unhandledException` behavior).  Would you prefer a separate issue for that?

**Comment by CrabDude** [comment]
@kevinoid Hmmm... That's a good point too. Callbacks are such a terrible abstraction.

To be clear, are you saying that `.nodeify` handles a callback shallow exception with an `uncaughtException` instead of `unhandledRejection`?

**Comment by CrabDude** [comment]
Done. [507717e...4a0732e (1.0 -> 1.1)](https://github.com/CrabDude/bluebird-nodeify/compare/507717ee2bdfec0e80a32865e98bbeeff6c908c5...4a0732e4a4cbe3a3f30767dc70564a8b1f0d5400)

**Comment by kevinoid** [comment]
They are indeed.  Sorry for the slow reply.  You figured out my meaning and fixed it.  That's excellent!  Thank you once again!
