### ISSUE TITLE
Unnecessary dependency on bluebird?

### ISSUE THREAD

**Issue by kevinoid** [CrabDude/bluebird-nodeify#2]
Why depend on bluebird only to re-export it from this module?

**Comment by CrabDude** [comment]
That's actually a good point. I used bluebird in one of the original versions, but obviously it's no longer getting used and should therefore be removed.

Thanks for pointing this out!

**Comment by kevinoid** [comment]
Much appreciated!

**Comment by CrabDude** [comment]
Done. [507717e...4a0732e (1.0 -> 1.1)](https://github.com/CrabDude/bluebird-nodeify/compare/507717ee2bdfec0e80a32865e98bbeeff6c908c5...4a0732e4a4cbe3a3f30767dc70564a8b1f0d5400)
